### ISSUE TITLE
Why use sprite-image instead of url?

### ISSUE THREAD

**Issue by gagarine** [hagenburger/lemonade#1]
I don't understand why you use a custom "sprite-image" declaration in the CSS instead of use url. If someone want to use sprite habitually they want for all. It would be better to check if the image is in a special directory and generate the sprite inside this directory too.

input
.seven-up {
  background: url("sprites/bottles/seven-up.png");
}

output
.seven-up {
  background: url("sprites/bottles/sprite-bottles.png");
}

or so it's easy to clean and rebuild the generated sprite
.seven-up {
  background: url("sprites/generated/bottles.png");
}

**Comment by hagenburger** [comment]
I don’t think it’s good to override the default `url()` function:
-    I don’t want all images to be a sprite (imagine a big background JPG—this shouldn’t be packed as PNG; here I want to setup the compression level in Photoshop)
-    I’m not sure if Sass/Compass would allow to override `url()`.
-    When you read the code, you know there will be a sprite (p. e. if a new developer will join the project)

If you want to generate the sprite inside of the directory is a matter of taste. I prefer the outside version just because it will generate less CSS code. This could be part of a configuration file in a future release if you want.

**Comment by gagarine** [comment]
"I don’t want all images to be a sprite (imagine a big background JPG—this shouldn’t be packed as PNG; here I want to setup the compression level in Photoshop)" 
Right. My idea is the trigger is the path ie "sprite/*" instead of a the special "sprite-image". The advantage I see:
-  CSS work with or without rewriting.
-  You can launch the rewriting when do you want (because it work without)

I'm sorry I'm not a ruby guy but I want eventually port the idea on a drupal module (PHP). So it need to work out of the box with all themes. I don't want to pack JPEG because you lose quality at each compression...
